"""change idempotency key to string

Revision ID: 8adcbaecf2e7
Revises: e1f741074fe0
Create Date: 2026-09-23 00:32:23.626489

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8adcbaecf2e7"
down_revision: str | Sequence[str] | None = "e1f741074fe0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "idempotency_key",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "idempotency_key",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
